- name: Install sysstat on debian
  ansible.builtin.apt:
    name:
      - sysstat
    state: present
  when: ansible_facts['os_family']|lower == 'debian'
- name: Install sysstat on redhat
  ansible.builtin.yum:
    name:
      - sysstat
    state: present
  when: ansible_facts['os_family']|lower == 'redhat'
